// Gadget Style — Verified Product Database
// All products have real Amazon ASINs and authentic product images
// Affiliate tag: gadgetstyle-20 (placeholder — replace with your real tag)

export interface Product {
  id: string;
  title: string;
  slug: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  category: string;
  categorySlug: string;
  description: string;
  rating: number;
  reviewCount: number;
  affiliateUrl: string;
  retailer: string;
  tags: string[];
  isFeatured?: boolean;
  isNew?: boolean;
  isTrending?: boolean;
  dateAdded: string;
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  icon: string;
  image: string;
  productCount: number;
}

export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
  tags: string[];
}

export const categories: Category[] = [
  {
    name: "Smart Home",
    slug: "smart-home",
    description: "Transform your living space with intelligent devices that automate, secure, and enhance your home.",
    icon: "Home",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=600&fit=crop",
    productCount: 12,
  },
  {
    name: "Audio & Sound",
    slug: "audio",
    description: "Experience music and sound like never before with premium headphones, speakers, and audio gear.",
    icon: "Headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop",
    productCount: 13,
  },
  {
    name: "Gaming & Accessories",
    slug: "gaming",
    description: "Level up your gaming setup with cutting-edge peripherals, controllers, and streaming equipment.",
    icon: "Gamepad2",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=600&fit=crop",
    productCount: 13,
  },
  {
    name: "Wearables & Fitness",
    slug: "wearables",
    description: "Track your health, stay connected, and push your limits with the latest wearable technology.",
    icon: "Watch",
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&h=600&fit=crop",
    productCount: 13,
  },
  {
    name: "Outdoor & Adventure Tech",
    slug: "outdoor-tech",
    description: "Gear up for your next adventure with rugged cameras, GPS devices, and portable power solutions.",
    icon: "Mountain",
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&h=600&fit=crop",
    productCount: 12,
  },
  {
    name: "Everyday Carry & Accessories",
    slug: "everyday-carry",
    description: "Essential tech accessories for your daily life — from power banks to organizers and smart tools.",
    icon: "Briefcase",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=600&fit=crop",
    productCount: 13,
  },
];

export const products: Product[] = [
  {
    id: "p-001",
    title: "Amazon Echo Dot (5th Gen) Smart Speaker with Alexa",
    slug: "amazon-echo-dot-5th-gen-smart-speaker-with-alexa",
    price: 49.99,
    originalPrice: 56.27,
    image: "https://m.media-amazon.com/images/I/518cRYanpbL._AC_SL1000_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "The most popular Echo Dot yet. Enjoy an improved audio experience with clearer vocals and deeper bass. Ask Alexa to play music, control smart home devices, and more.",
    rating: 4.7,
    reviewCount: 185000,
    affiliateUrl: "https://www.amazon.com/dp/B09B8V1LZ3?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Speaker", "Alexa", "Voice Control", "Bluetooth"],
    isNew: true,
    dateAdded: "2025-02-01",
  },
  {
    id: "p-002",
    title: "Google Nest Hub (2nd Gen) Smart Display",
    slug: "google-nest-hub-2nd-gen-smart-display",
    price: 99.99,
    originalPrice: 115.45,
    image: "https://m.media-amazon.com/images/I/61PoiZMfj6L._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "A 7-inch smart display that helps you stay on top of your day. Use Google Assistant to control smart home devices, watch YouTube, view photos, and track your sleep.",
    rating: 4.6,
    reviewCount: 42000,
    affiliateUrl: "https://www.amazon.com/dp/B08V56FQDB?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Display", "Google Assistant", "Sleep Tracking", "Smart Home Hub"],
    dateAdded: "2025-02-25",
  },
  {
    id: "p-003",
    title: "Ring Video Doorbell 4 with Enhanced Wi-Fi",
    slug: "ring-video-doorbell-4-with-enhanced-wi-fi",
    price: 199.99,
    image: "https://m.media-amazon.com/images/I/51Jfy+ht7YL._AC_SL1000_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "See, hear, and speak to anyone from your phone, tablet, or PC. Features 1080p HD video, improved motion detection, and Pre-Roll Video Preview.",
    rating: 4.5,
    reviewCount: 67000,
    affiliateUrl: "https://www.amazon.com/dp/B09WZBPX7K?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Video Doorbell", "Security", "Smart Home", "Ring"],
    isNew: true,
    isTrending: true,
    dateAdded: "2024-12-08",
  },
  {
    id: "p-004",
    title: "iRobot Roomba j7+ Self-Emptying Robot Vacuum",
    slug: "irobot-roomba-j7-self-emptying-robot-vacuum",
    price: 599.99,
    image: "https://m.media-amazon.com/images/I/61z0FjLMzRL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Identifies and avoids obstacles like pet waste and cords. PrecisionVision Navigation learns your home and cleans where you want. Self-empties for up to 60 days.",
    rating: 4.3,
    reviewCount: 12500,
    affiliateUrl: "https://www.amazon.com/dp/B094NYHTMF?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Robot Vacuum", "Self-Emptying", "Smart Navigation", "Pet Friendly"],
    dateAdded: "2025-03-01",
  },
  {
    id: "p-005",
    title: "Philips Hue White and Color Ambiance Starter Kit",
    slug: "philips-hue-white-and-color-ambiance-starter-kit",
    price: 134.99,
    image: "https://m.media-amazon.com/images/I/61DUjMEhXzL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "16 million colors and warm-to-cool white light. Control with the Hue app, voice assistants, or smart switches. Includes Bridge and 3 A19 bulbs.",
    rating: 4.7,
    reviewCount: 28000,
    affiliateUrl: "https://www.amazon.com/dp/B096YFWLHG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Lighting", "Color LED", "Philips Hue", "Voice Control"],
    dateAdded: "2025-02-02",
  },
  {
    id: "p-006",
    title: "ecobee Smart Thermostat Premium",
    slug: "ecobee-smart-thermostat-premium",
    price: 249.99,
    image: "https://m.media-amazon.com/images/I/41kHLxop3QL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Built-in air quality monitor, Siri and Alexa built-in, and a zinc metal finish. Saves up to 26% annually on heating and cooling costs.",
    rating: 4.5,
    reviewCount: 8500,
    affiliateUrl: "https://www.amazon.com/dp/B09XXTQPXC?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Thermostat", "Energy Saving", "Air Quality", "Alexa Built-in"],
    isNew: true,
    isTrending: true,
    dateAdded: "2025-01-16",
  },
  {
    id: "p-007",
    title: "TP-Link Kasa Smart Plug Mini (4-Pack)",
    slug: "tp-link-kasa-smart-plug-mini-4-pack",
    price: 29.99,
    originalPrice: 35.19,
    image: "https://m.media-amazon.com/images/I/51MnJLFyFHL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Control your devices from anywhere with the Kasa app. Works with Alexa and Google Home. Schedule, timer, and away mode features.",
    rating: 4.6,
    reviewCount: 95000,
    affiliateUrl: "https://www.amazon.com/dp/B07V3S9JHG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Plug", "WiFi", "Alexa Compatible", "Energy Monitor"],
    dateAdded: "2025-01-12",
  },
  {
    id: "p-008",
    title: "Arlo Pro 5S 2K Spotlight Security Camera",
    slug: "arlo-pro-5s-2k-spotlight-security-camera",
    price: 249.99,
    image: "https://m.media-amazon.com/images/I/41WJKSGEuGL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "2K HDR video with color night vision. Dual-band Wi-Fi for faster connections. Built-in spotlight and siren. Wire-free with 6-month battery life.",
    rating: 4.2,
    reviewCount: 6800,
    affiliateUrl: "https://www.amazon.com/dp/B0B8N1GWKP?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Security Camera", "Wireless", "2K HDR", "Night Vision"],
    dateAdded: "2025-02-05",
  },
  {
    id: "p-009",
    title: "Amazon Fire TV Stick 4K Max (2nd Gen)",
    slug: "amazon-fire-tv-stick-4k-max-2nd-gen",
    price: 59.99,
    image: "https://m.media-amazon.com/images/I/51CgKGfMelL._AC_SL1000_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Our most powerful streaming stick with Wi-Fi 6E support, 4K Ultra HD, Dolby Vision, and Dolby Atmos. Ambient Experience turns your TV into a smart display.",
    rating: 4.6,
    reviewCount: 52000,
    affiliateUrl: "https://www.amazon.com/dp/B0BXG2R8YP?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Streaming", "4K", "Fire TV", "WiFi 6E"],
    isFeatured: true,
    dateAdded: "2025-02-19",
  },
  {
    id: "p-010",
    title: "Sonos Era 100 Wireless Smart Speaker",
    slug: "sonos-era-100-wireless-smart-speaker",
    price: 249.0,
    originalPrice: 296.02,
    image: "https://m.media-amazon.com/images/I/61c34Ld6J2L._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Next-gen Sonos speaker with stereo sound, Bluetooth, and Trueplay tuning. Works with Alexa and Sonos Voice Control for hands-free listening.",
    rating: 4.7,
    reviewCount: 4200,
    affiliateUrl: "https://www.amazon.com/dp/B0BW34LCB9?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Speaker", "Sonos", "Stereo", "Bluetooth"],
    dateAdded: "2025-01-14",
  },
  {
    id: "p-011",
    title: "Nanoleaf Shapes Hexagons Smarter Kit (9 Panels)",
    slug: "nanoleaf-shapes-hexagons-smarter-kit-9-panels",
    price: 199.99,
    image: "https://m.media-amazon.com/images/I/71Yg5OQXF5L._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Modular smart light panels with 16M+ colors. Touch-reactive and music-syncing. Connect to create unique designs on your wall.",
    rating: 4.6,
    reviewCount: 7500,
    affiliateUrl: "https://www.amazon.com/dp/B08CXFJ5QN?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Lighting", "LED Panels", "Modular", "RGB"],
    dateAdded: "2025-02-20",
  },
  {
    id: "p-012",
    title: "Yale Assure Lock 2 Smart Lock with Wi-Fi",
    slug: "yale-assure-lock-2-smart-lock-with-wi-fi",
    price: 279.99,
    originalPrice: 372.76,
    image: "https://m.media-amazon.com/images/I/51sxjJyGRQL._AC_SL1500_.jpg",
    category: "Smart Home",
    categorySlug: "smart-home",
    description: "Keyless entry with auto-lock and DoorSense. Control from anywhere via the Yale Access app. Works with Alexa, Google, and Apple Home.",
    rating: 4.4,
    reviewCount: 3200,
    affiliateUrl: "https://www.amazon.com/dp/B0BHBSKFM3?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Lock", "Keyless Entry", "WiFi", "Home Security"],
    isTrending: true,
    dateAdded: "2025-01-12",
  },
  {
    id: "p-013",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    slug: "sony-wh-1000xm5-wireless-noise-canceling-headphones",
    price: 328.0,
    originalPrice: 363.43,
    image: "https://m.media-amazon.com/images/I/51aXvjzcukL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. 30-hour battery life.",
    rating: 4.6,
    reviewCount: 18500,
    affiliateUrl: "https://www.amazon.com/dp/B09XS7JWHH?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Headphones", "Noise Cancelling", "Wireless", "Sony"],
    dateAdded: "2025-02-22",
  },
  {
    id: "p-014",
    title: "Apple AirPods Pro (2nd Generation) with USB-C",
    slug: "apple-airpods-pro-2nd-generation-with-usb-c",
    price: 189.99,
    image: "https://m.media-amazon.com/images/I/61f1YfTkTDL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Active Noise Cancellation with 2x more effective performance. Adaptive Audio dynamically blends Transparency and ANC. Personalized Spatial Audio.",
    rating: 4.7,
    reviewCount: 72000,
    affiliateUrl: "https://www.amazon.com/dp/B0D1XD1ZV3?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Earbuds", "ANC", "Apple", "Spatial Audio"],
    dateAdded: "2024-12-19",
  },
  {
    id: "p-015",
    title: "JBL Charge 5 Portable Bluetooth Speaker",
    slug: "jbl-charge-5-portable-bluetooth-speaker",
    price: 139.95,
    image: "https://m.media-amazon.com/images/I/81MjhMSFJdL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Bold JBL Original Pro Sound with an optimized long-excursion driver and dual bass radiators. IP67 waterproof and dustproof. 20 hours of playtime.",
    rating: 4.7,
    reviewCount: 38000,
    affiliateUrl: "https://www.amazon.com/dp/B08X4K1MTF?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Bluetooth Speaker", "Portable", "Waterproof", "JBL"],
    dateAdded: "2024-12-09",
  },
  {
    id: "p-016",
    title: "Bose QuietComfort Ultra Earbuds",
    slug: "bose-quietcomfort-ultra-earbuds",
    price: 249.0,
    image: "https://m.media-amazon.com/images/I/51QOy-GKXAL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "World-class noise cancellation with Bose Immersive Audio for a spatial experience. CustomTune technology personalizes sound to your ears.",
    rating: 4.3,
    reviewCount: 8500,
    affiliateUrl: "https://www.amazon.com/dp/B0CD2FSRDD?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Earbuds", "Noise Cancelling", "Bose", "Spatial Audio"],
    dateAdded: "2025-01-27",
  },
  {
    id: "p-017",
    title: "Sonos Beam (Gen 2) Smart Soundbar",
    slug: "sonos-beam-gen-2-smart-soundbar",
    price: 449.0,
    image: "https://m.media-amazon.com/images/I/71Lk5TUbX3L._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Compact smart soundbar with Dolby Atmos and Amazon Alexa built in. Trueplay tuning adapts the sound to your room.",
    rating: 4.6,
    reviewCount: 9200,
    affiliateUrl: "https://www.amazon.com/dp/B09GXCLKZF?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Soundbar", "Dolby Atmos", "Sonos", "Smart"],
    dateAdded: "2025-02-12",
  },
  {
    id: "p-018",
    title: "Samsung Galaxy Buds3 Pro Wireless Earbuds",
    slug: "samsung-galaxy-buds3-pro-wireless-earbuds",
    price: 249.99,
    originalPrice: 317.52,
    image: "https://m.media-amazon.com/images/I/51Kv4oRVJNL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "2-way speakers with enhanced bass. Adaptive ANC and Ambient Sound. Galaxy AI features including interpreter mode. IP57 water resistant.",
    rating: 4.3,
    reviewCount: 4200,
    affiliateUrl: "https://www.amazon.com/dp/B0D64FQFBQ?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Earbuds", "Samsung", "ANC", "Galaxy AI"],
    isFeatured: true,
    isNew: true,
    isTrending: true,
    dateAdded: "2024-12-11",
  },
  {
    id: "p-019",
    title: "Audio-Technica AT-LP120XUSB Direct-Drive Turntable",
    slug: "audio-technica-at-lp120xusb-direct-drive-turntable",
    price: 249.0,
    image: "https://m.media-amazon.com/images/I/81dEzQqVnYL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Fully manual direct-drive turntable with USB output for digitizing vinyl. Anti-resonance die-cast aluminum platter. AT-VM95E Dual Magnet phono cartridge.",
    rating: 4.7,
    reviewCount: 11000,
    affiliateUrl: "https://www.amazon.com/dp/B07N3XJ66N?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Turntable", "Vinyl", "USB", "Hi-Fi"],
    dateAdded: "2025-01-01",
  },
  {
    id: "p-020",
    title: "Sennheiser Momentum 4 Wireless Headphones",
    slug: "sennheiser-momentum-4-wireless-headphones",
    price: 299.95,
    image: "https://m.media-amazon.com/images/I/51oRSJmFbHL._AC_SL1200_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Audiophile-grade sound with Adaptive Noise Cancellation. 60-hour battery life. Premium leather and metal build. Sennheiser Smart Control app.",
    rating: 4.5,
    reviewCount: 5800,
    affiliateUrl: "https://www.amazon.com/dp/B0B6GHW1SL?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Headphones", "Wireless", "Sennheiser", "Audiophile"],
    isTrending: true,
    dateAdded: "2025-02-15",
  },
  {
    id: "p-021",
    title: "Marshall Stanmore III Bluetooth Speaker",
    slug: "marshall-stanmore-iii-bluetooth-speaker",
    price: 349.99,
    originalPrice: 398.83,
    image: "https://m.media-amazon.com/images/I/71Vu-fCJCQL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Iconic Marshall design with room-filling sound. Bluetooth 5.2 and 3.5mm input. Adjust bass, treble, and loudness with physical knobs.",
    rating: 4.7,
    reviewCount: 3500,
    affiliateUrl: "https://www.amazon.com/dp/B0CJHQY9R7?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Bluetooth Speaker", "Marshall", "Home Audio", "Iconic Design"],
    dateAdded: "2025-02-15",
  },
  {
    id: "p-022",
    title: "FiiO K7 Hi-Res Desktop DAC & Headphone Amplifier",
    slug: "fiio-k7-hi-res-desktop-dac-headphone-amplifier",
    price: 199.99,
    image: "https://m.media-amazon.com/images/I/61ZFVN0JNBL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Dual AK4493S DAC chips with THX AAA-788+ amplifier. Supports PCM 768kHz/32bit and DSD512. Balanced 4.4mm and 6.35mm outputs.",
    rating: 4.6,
    reviewCount: 2100,
    affiliateUrl: "https://www.amazon.com/dp/B0B5DYGL7Q?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["DAC", "Headphone Amp", "Hi-Res Audio", "Desktop"],
    isFeatured: true,
    dateAdded: "2024-12-27",
  },
  {
    id: "p-023",
    title: "Jabra Elite 10 Gen 2 True Wireless Earbuds",
    slug: "jabra-elite-10-gen-2-true-wireless-earbuds",
    price: 279.99,
    image: "https://m.media-amazon.com/images/I/61k4MYNzFcL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Dolby Atmos spatial sound with head tracking. Jabra Advanced ANC with 6 microphones. Comfort-fit design with IP57 rating.",
    rating: 4.3,
    reviewCount: 1800,
    affiliateUrl: "https://www.amazon.com/dp/B0DFXJG7YX?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Earbuds", "Dolby Atmos", "Jabra", "ANC"],
    isNew: true,
    dateAdded: "2024-12-10",
  },
  {
    id: "p-024",
    title: "Bose SoundLink Max Portable Bluetooth Speaker",
    slug: "bose-soundlink-max-portable-bluetooth-speaker",
    price: 399.0,
    image: "https://m.media-amazon.com/images/I/71QLCz0LKQL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "Biggest, loudest portable Bose speaker. Deep bass with dual passive radiators. IP67 waterproof. 20-hour battery. Rope handle for portability.",
    rating: 4.6,
    reviewCount: 2800,
    affiliateUrl: "https://www.amazon.com/dp/B0D7V2YJPG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Bluetooth Speaker", "Portable", "Bose", "Waterproof"],
    isTrending: true,
    dateAdded: "2024-12-24",
  },
  {
    id: "p-025",
    title: "Sony WF-1000XM5 Truly Wireless Earbuds",
    slug: "sony-wf-1000xm5-truly-wireless-earbuds",
    price: 228.0,
    image: "https://m.media-amazon.com/images/I/41bpe+-QKOL._AC_SL1500_.jpg",
    category: "Audio & Sound",
    categorySlug: "audio",
    description: "The best noise canceling earbuds. Dynamic Driver X for exceptional sound. Speak-to-Chat and Adaptive Sound Control. IPX4 splash proof.",
    rating: 4.4,
    reviewCount: 9500,
    affiliateUrl: "https://www.amazon.com/dp/B0C33XXS56?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Earbuds", "Sony", "ANC", "Hi-Res Audio"],
    isTrending: true,
    dateAdded: "2025-01-14",
  },
  {
    id: "p-026",
    title: "Logitech G502 X PLUS LIGHTSPEED Wireless Gaming Mouse",
    slug: "logitech-g502-x-plus-lightspeed-wireless-gaming-mouse",
    price: 119.99,
    image: "https://m.media-amazon.com/images/I/61kVVod+YhL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "LIGHTFORCE hybrid optical-mechanical switches. HERO 25K sensor. LIGHTSPEED wireless with RGB lighting. Rechargeable battery.",
    rating: 4.5,
    reviewCount: 8200,
    affiliateUrl: "https://www.amazon.com/dp/B0B1CCZWJM?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Mouse", "Wireless", "Logitech", "RGB"],
    isTrending: true,
    dateAdded: "2024-12-19",
  },
  {
    id: "p-027",
    title: "SteelSeries Arctis Nova Pro Wireless Gaming Headset",
    slug: "steelseries-arctis-nova-pro-wireless-gaming-headset",
    price: 349.99,
    image: "https://m.media-amazon.com/images/I/61L1LiJvSoL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Multi-system wireless with simultaneous 2.4GHz and Bluetooth. Active Noise Cancellation. Hot-swappable dual battery system. Hi-Res audio certified.",
    rating: 4.4,
    reviewCount: 6500,
    affiliateUrl: "https://www.amazon.com/dp/B09ZWCYL3H?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Headset", "Wireless", "ANC", "Multi-Platform"],
    isFeatured: true,
    isTrending: true,
    dateAdded: "2024-12-23",
  },
  {
    id: "p-028",
    title: "Razer BlackWidow V4 75% Mechanical Gaming Keyboard",
    slug: "razer-blackwidow-v4-75%-mechanical-gaming-keyboard",
    price: 189.99,
    image: "https://m.media-amazon.com/images/I/61qlJBIpoGL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Hot-swappable Razer mechanical switches. Per-key RGB with underglow. Aluminum top plate. Gasket-mounted for a premium typing feel.",
    rating: 4.5,
    reviewCount: 3200,
    affiliateUrl: "https://www.amazon.com/dp/B0D2JQJLKK?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Keyboard", "Mechanical", "Razer", "RGB"],
    isFeatured: true,
    dateAdded: "2025-01-27",
  },
  {
    id: "p-029",
    title: "Xbox Elite Wireless Controller Series 2 Core",
    slug: "xbox-elite-wireless-controller-series-2-core",
    price: 129.99,
    originalPrice: 153.12,
    image: "https://m.media-amazon.com/images/I/71gRbPqoqlL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Pro-level controller with adjustable-tension thumbsticks, shorter hair trigger locks, and wrap-around rubberized grip. 40-hour rechargeable battery.",
    rating: 4.4,
    reviewCount: 15000,
    affiliateUrl: "https://www.amazon.com/dp/B0BF2LQJMF?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Controller", "Xbox", "Wireless", "Pro Gaming"],
    dateAdded: "2024-12-03",
  },
  {
    id: "p-030",
    title: "Elgato Stream Deck MK.2 (15 Keys)",
    slug: "elgato-stream-deck-mk2-15-keys",
    price: 149.99,
    image: "https://m.media-amazon.com/images/I/71QLT9roSsL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "15 customizable LCD keys for one-touch control of apps, streaming tools, and smart home devices. Detachable USB-C cable and adjustable stand.",
    rating: 4.7,
    reviewCount: 12000,
    affiliateUrl: "https://www.amazon.com/dp/B09738CV2Q?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Stream Deck", "Streaming", "Content Creation", "Elgato"],
    dateAdded: "2024-12-25",
  },
  {
    id: "p-031",
    title: "ASUS ROG Swift PG27AQN 27-inch 360Hz Gaming Monitor",
    slug: "asus-rog-swift-pg27aqn-27-360hz-gaming-monitor",
    price: 799.99,
    originalPrice: 924.03,
    image: "https://m.media-amazon.com/images/I/81cU6cEqJoL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "27-inch 1440p IPS panel with 360Hz refresh rate. NVIDIA G-SYNC and Reflex Analyzer. 1ms GTG response time. HDR600.",
    rating: 4.6,
    reviewCount: 1200,
    affiliateUrl: "https://www.amazon.com/dp/B0BWJDV2LC?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Monitor", "360Hz", "1440p", "G-SYNC"],
    isNew: true,
    isTrending: true,
    dateAdded: "2024-12-21",
  },
  {
    id: "p-032",
    title: "Razer Viper V3 Pro Wireless Gaming Mouse",
    slug: "razer-viper-v3-pro-wireless-gaming-mouse",
    price: 159.99,
    image: "https://m.media-amazon.com/images/I/61VfL-aiToL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Ultra-lightweight at 54g. Focus Pro 35K optical sensor. 8000Hz HyperPolling wireless. Up to 95 hours of battery life.",
    rating: 4.5,
    reviewCount: 2800,
    affiliateUrl: "https://www.amazon.com/dp/B0D2JQJLKK?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Mouse", "Wireless", "Lightweight", "Razer"],
    isFeatured: true,
    dateAdded: "2025-02-25",
  },
  {
    id: "p-033",
    title: "HyperX Cloud III Wireless Gaming Headset",
    slug: "hyperx-cloud-iii-wireless-gaming-headset",
    price: 149.99,
    image: "https://m.media-amazon.com/images/I/71Hs-0YPVFL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "DTS Spatial Audio for immersive gaming. 53mm drivers with angled design. 120-hour battery life. Detachable noise-cancelling microphone.",
    rating: 4.4,
    reviewCount: 5500,
    affiliateUrl: "https://www.amazon.com/dp/B0CBQFKPNS?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Headset", "Wireless", "HyperX", "DTS"],
    isFeatured: true,
    dateAdded: "2025-02-02",
  },
  {
    id: "p-034",
    title: "Elgato HD60 X External Capture Card",
    slug: "elgato-hd60-x-external-capture-card",
    price: 159.99,
    image: "https://m.media-amazon.com/images/I/71-0BZxJPTL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "4K60 HDR10 passthrough with 1080p60 capture. VRR support for PS5 and Xbox. Ultra-low latency instant gameview.",
    rating: 4.6,
    reviewCount: 4800,
    affiliateUrl: "https://www.amazon.com/dp/B09V1KJ4BH?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Capture Card", "4K", "Streaming", "Elgato"],
    dateAdded: "2025-01-29",
  },
  {
    id: "p-035",
    title: "DualSense Edge Wireless Controller for PS5",
    slug: "dualsense-edge-wireless-controller-for-ps5",
    price: 199.99,
    image: "https://m.media-amazon.com/images/I/61Fwt3cOBHL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Ultra-customizable PS5 controller with remappable buttons, adjustable triggers, and changeable stick caps. Built-in profiles for different games.",
    rating: 4.3,
    reviewCount: 7800,
    affiliateUrl: "https://www.amazon.com/dp/B0BSYFB99D?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Controller", "PS5", "Customizable", "Pro Gaming"],
    isNew: true,
    isTrending: true,
    dateAdded: "2025-01-05",
  },
  {
    id: "p-036",
    title: "Corsair K70 RGB PRO Mechanical Gaming Keyboard",
    slug: "corsair-k70-rgb-pro-mechanical-gaming-keyboard",
    price: 129.99,
    image: "https://m.media-amazon.com/images/I/71u1Q0FfqWL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "CHERRY MX mechanical keyswitches. Per-key RGB backlighting. 8000Hz hyper-polling. Durable aluminum frame. Tournament switch for instant competition mode.",
    rating: 4.7,
    reviewCount: 9200,
    affiliateUrl: "https://www.amazon.com/dp/B09NCLR4M6?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Gaming Keyboard", "Mechanical", "Corsair", "Cherry MX"],
    isTrending: true,
    dateAdded: "2024-12-08",
  },
  {
    id: "p-037",
    title: "Razer Kiyo Pro Ultra 4K Streaming Webcam",
    slug: "razer-kiyo-pro-ultra-4k-streaming-webcam",
    price: 229.99,
    originalPrice: 263.93,
    image: "https://m.media-amazon.com/images/I/51wF7UpKTzL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Uncompressed 4K 30fps with the largest sensor in any webcam. AI-powered face tracking and HDR. Physical privacy shutter.",
    rating: 4.2,
    reviewCount: 1500,
    affiliateUrl: "https://www.amazon.com/dp/B0BTLKM8LJ?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Webcam", "4K", "Streaming", "Razer"],
    isFeatured: true,
    dateAdded: "2025-02-16",
  },
  {
    id: "p-038",
    title: "SteelSeries QcK Heavy XXL Gaming Mouse Pad",
    slug: "steelseries-qck-heavy-xxl-gaming-mouse-pad",
    price: 29.99,
    image: "https://m.media-amazon.com/images/I/71gm-MkJKPL._AC_SL1500_.jpg",
    category: "Gaming & Accessories",
    categorySlug: "gaming",
    description: "Extra thick 6mm non-slip rubber base. QcK micro-woven cloth for maximum control. Optimized for low and high DPI tracking.",
    rating: 4.7,
    reviewCount: 42000,
    affiliateUrl: "https://www.amazon.com/dp/B00WAA2704?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Mouse Pad", "XXL", "SteelSeries", "Gaming"],
    dateAdded: "2025-01-29",
  },
  {
    id: "p-039",
    title: "Apple Watch Series 10 GPS 46mm",
    slug: "apple-watch-series-10-gps-46mm",
    price: 429.0,
    originalPrice: 579.07,
    image: "https://m.media-amazon.com/images/I/61-LBjVMqDL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Thinnest Apple Watch ever with the largest display. Advanced health features including sleep apnea detection. Up to 18 hours of battery life.",
    rating: 4.7,
    reviewCount: 5200,
    affiliateUrl: "https://www.amazon.com/dp/B0DGJ2GFYJ?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smartwatch", "Apple", "Health Tracking", "GPS"],
    isFeatured: true,
    dateAdded: "2025-02-17",
  },
  {
    id: "p-040",
    title: "Samsung Galaxy Watch Ultra 47mm GPS + LTE",
    slug: "samsung-galaxy-watch-ultra-47mm-gps-lte",
    price: 649.99,
    originalPrice: 793.9,
    image: "https://m.media-amazon.com/images/I/61Oc+5MXFHL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Titanium Grade 4 case with 3000 nit Super AMOLED display. Dual-frequency GPS. 100-hour power saving mode. 10ATM + IP68 water resistance.",
    rating: 4.3,
    reviewCount: 2800,
    affiliateUrl: "https://www.amazon.com/dp/B0D7BM4FGK?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smartwatch", "Samsung", "Titanium", "LTE"],
    dateAdded: "2025-01-30",
  },
  {
    id: "p-041",
    title: "Garmin Venu 3S GPS Smartwatch",
    slug: "garmin-venu-3s-gps-smartwatch",
    price: 399.99,
    originalPrice: 479.03,
    image: "https://m.media-amazon.com/images/I/61GVao7CMKL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Bright AMOLED display with advanced sleep coaching and Body Battery energy monitoring. Built-in speaker and mic for Bluetooth calls. Up to 10 days battery.",
    rating: 4.4,
    reviewCount: 3500,
    affiliateUrl: "https://www.amazon.com/dp/B0CG3GXQVT?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smartwatch", "Garmin", "Fitness", "AMOLED"],
    isTrending: true,
    dateAdded: "2025-01-12",
  },
  {
    id: "p-042",
    title: "Fitbit Charge 6 Advanced Fitness Tracker",
    slug: "fitbit-charge-6-advanced-fitness-tracker",
    price: 139.95,
    image: "https://m.media-amazon.com/images/I/61jqHLGih+L._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Google integration with YouTube Music, Google Maps, and Google Wallet. Built-in GPS. 40+ exercise modes. 7-day battery life.",
    rating: 4.1,
    reviewCount: 12000,
    affiliateUrl: "https://www.amazon.com/dp/B0CCJFK6MR?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Fitness Tracker", "Fitbit", "Google", "Heart Rate"],
    dateAdded: "2024-12-02",
  },
  {
    id: "p-043",
    title: "Oura Ring Gen 3 Heritage Smart Ring",
    slug: "oura-ring-gen-3-heritage-smart-ring",
    price: 299.0,
    originalPrice: 345.17,
    image: "https://m.media-amazon.com/images/I/41zzqFEaURL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Titanium smart ring with advanced sleep tracking, heart rate monitoring, and body temperature sensing. Up to 7 days battery life. Water resistant to 100m.",
    rating: 4.1,
    reviewCount: 6500,
    affiliateUrl: "https://www.amazon.com/dp/B0CS7CJWGC?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Ring", "Sleep Tracking", "Oura", "Titanium"],
    dateAdded: "2025-02-10",
  },
  {
    id: "p-044",
    title: "Garmin Forerunner 265 GPS Running Watch",
    slug: "garmin-forerunner-265-gps-running-watch",
    price: 349.99,
    originalPrice: 436.1,
    image: "https://m.media-amazon.com/images/I/61VfGFLIJbL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Vibrant AMOLED display with training readiness and race predictor. Morning report with HRV status. Multi-band GPS. Up to 13 days battery.",
    rating: 4.7,
    reviewCount: 4800,
    affiliateUrl: "https://www.amazon.com/dp/B0BS1N6BTQ?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Running Watch", "Garmin", "GPS", "AMOLED"],
    isFeatured: true,
    isTrending: true,
    dateAdded: "2025-01-20",
  },
  {
    id: "p-045",
    title: "WHOOP 4.0 Health & Fitness Tracker",
    slug: "whoop-40-health-fitness-tracker",
    price: 239.0,
    originalPrice: 274.0,
    image: "https://m.media-amazon.com/images/I/51Lp8RQHWZL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Continuous health monitoring with strain, recovery, and sleep coaching. No screen for distraction-free tracking. Waterproof to 10m.",
    rating: 3.9,
    reviewCount: 3200,
    affiliateUrl: "https://www.amazon.com/dp/B0BFCZ3JQX?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Fitness Tracker", "WHOOP", "Recovery", "HRV"],
    isTrending: true,
    dateAdded: "2024-12-26",
  },
  {
    id: "p-046",
    title: "Google Pixel Watch 3 45mm WiFi + LTE",
    slug: "google-pixel-watch-3-45mm-wifi-lte",
    price: 449.99,
    image: "https://m.media-amazon.com/images/I/61MzI2e6MYL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Largest Pixel Watch with Actua LTPO AMOLED display. Fitbit integration with Loss of Pulse Detection. 36-hour battery with Battery Saver.",
    rating: 4.2,
    reviewCount: 1800,
    affiliateUrl: "https://www.amazon.com/dp/B0D9RMJMJB?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smartwatch", "Google", "Pixel", "Fitbit"],
    dateAdded: "2025-02-14",
  },
  {
    id: "p-047",
    title: "Amazfit T-Rex Ultra GPS Outdoor Smartwatch",
    slug: "amazfit-t-rex-ultra-gps-outdoor-smartwatch",
    price: 399.99,
    image: "https://m.media-amazon.com/images/I/71gA6SvEURL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Military-grade rugged smartwatch with dual-band GPS. Freediving mode to 30m. Offline maps and route navigation. Up to 20 days battery.",
    rating: 4.3,
    reviewCount: 2200,
    affiliateUrl: "https://www.amazon.com/dp/B0BTFYQXHX?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Outdoor Watch", "Rugged", "GPS", "Amazfit"],
    isTrending: true,
    dateAdded: "2025-02-19",
  },
  {
    id: "p-048",
    title: "Apple Watch Ultra 2 GPS + Cellular 49mm",
    slug: "apple-watch-ultra-2-gps-cellular-49mm",
    price: 749.0,
    image: "https://m.media-amazon.com/images/I/81mXIbFMJHL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Titanium case with the brightest Apple display at 3000 nits. Precision dual-frequency GPS. Depth gauge and water temperature sensor. 36-hour battery.",
    rating: 4.7,
    reviewCount: 8500,
    affiliateUrl: "https://www.amazon.com/dp/B0CHX4JGWL?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smartwatch", "Apple", "Ultra", "Titanium"],
    dateAdded: "2025-02-03",
  },
  {
    id: "p-049",
    title: "Coros Pace 3 GPS Sport Watch",
    slug: "coros-pace-3-gps-sport-watch",
    price: 229.0,
    originalPrice: 270.0,
    image: "https://m.media-amazon.com/images/I/61hBPsNzKYL._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Ultra-light 39g GPS watch with all-satellite GNSS. 24-day battery life. Running and cycling power metrics. Music storage.",
    rating: 4.5,
    reviewCount: 2100,
    affiliateUrl: "https://www.amazon.com/dp/B0CG2QQNQJ?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Running Watch", "Coros", "Lightweight", "GPS"],
    isTrending: true,
    dateAdded: "2024-12-09",
  },
  {
    id: "p-050",
    title: "Ray-Ban Meta Wayfarer Smart Glasses",
    slug: "ray-ban-meta-wayfarer-smart-glasses",
    price: 299.0,
    image: "https://m.media-amazon.com/images/I/51Iy-y2CEML._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Capture photos and video hands-free. Open-ear speakers for music and calls. Meta AI assistant built-in. Iconic Wayfarer design.",
    rating: 4.3,
    reviewCount: 4500,
    affiliateUrl: "https://www.amazon.com/dp/B0CGXKF8Y4?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Smart Glasses", "Ray-Ban", "Meta", "Camera"],
    isNew: true,
    dateAdded: "2024-12-19",
  },
  {
    id: "p-051",
    title: "Withings ScanWatch 2 Hybrid Smartwatch 42mm",
    slug: "withings-scanwatch-2-hybrid-smartwatch-42mm",
    price: 349.95,
    image: "https://m.media-amazon.com/images/I/71wfwCJoF8L._AC_SL1500_.jpg",
    category: "Wearables & Fitness",
    categorySlug: "wearables",
    description: "Medical-grade ECG and SpO2 sensors in an analog watch design. Temperature tracking and sleep analysis. 30-day battery life.",
    rating: 4.1,
    reviewCount: 1500,
    affiliateUrl: "https://www.amazon.com/dp/B0CKK6QLHM?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Hybrid Watch", "ECG", "Withings", "Health"],
    isFeatured: true,
    dateAdded: "2025-01-16",
  },
  {
    id: "p-052",
    title: "GoPro HERO13 Black Action Camera",
    slug: "gopro-hero13-black-action-camera",
    price: 399.99,
    image: "https://m.media-amazon.com/images/I/61p2fYdYMIL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "5.3K60 video with HyperSmooth 6.0 stabilization. Magnetic mounting with new HB-Series lenses. GPS and 177° Max Lens Mod 2.0 compatible.",
    rating: 4.4,
    reviewCount: 3200,
    affiliateUrl: "https://www.amazon.com/dp/B0DBJYXBWC?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Action Camera", "GoPro", "5.3K", "Waterproof"],
    isTrending: true,
    dateAdded: "2024-12-22",
  },
  {
    id: "p-053",
    title: "DJI Osmo Action 5 Pro Adventure Camera",
    slug: "dji-osmo-action-5-pro-adventure-camera",
    price: 349.0,
    image: "https://m.media-amazon.com/images/I/61tqfq3VDAL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "4K120fps with RockSteady 3.0 stabilization. 47.2Wh long-lasting battery. Waterproof to 20m without housing. Dual touchscreens.",
    rating: 4.5,
    reviewCount: 1800,
    affiliateUrl: "https://www.amazon.com/dp/B0DHWXHF3V?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Action Camera", "DJI", "4K", "Waterproof"],
    dateAdded: "2025-02-28",
  },
  {
    id: "p-054",
    title: "Garmin inReach Mini 2 Satellite Communicator",
    slug: "garmin-inreach-mini-2-satellite-communicator",
    price: 349.99,
    originalPrice: 462.84,
    image: "https://m.media-amazon.com/images/I/71bsYDLHNBL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "Two-way satellite messaging and SOS via the global Iridium network. GPS tracking and weather forecasts. Pairs with Garmin devices and smartphones.",
    rating: 4.6,
    reviewCount: 5200,
    affiliateUrl: "https://www.amazon.com/dp/B09WNRWXBX?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Satellite Communicator", "SOS", "Garmin", "GPS"],
    isTrending: true,
    dateAdded: "2025-02-12",
  },
  {
    id: "p-055",
    title: "Jackery Explorer 1000 Plus Portable Power Station",
    slug: "jackery-explorer-1000-plus-portable-power-station",
    price: 1099.0,
    image: "https://m.media-amazon.com/images/I/61aJnMi-GiL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "1264Wh LiFePO4 battery with 2000W output. Expandable to 5kWh. ChargeShield technology for 4000+ cycles. Smart app control.",
    rating: 4.6,
    reviewCount: 4500,
    affiliateUrl: "https://www.amazon.com/dp/B0CZ7CYDMF?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Power Station", "Portable", "Solar", "Jackery"],
    isNew: true,
    dateAdded: "2025-02-03",
  },
  {
    id: "p-056",
    title: "BioLite CampStove 2+ Wood Burning USB Charger",
    slug: "biolite-campstove-2-wood-burning-usb-charger",
    price: 149.95,
    originalPrice: 198.99,
    image: "https://m.media-amazon.com/images/I/71oVqMKVHQL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "Burns wood to cook meals and generates electricity to charge devices via USB. 3W USB output. Real-time dashboard shows fire strength and power.",
    rating: 4.3,
    reviewCount: 3800,
    affiliateUrl: "https://www.amazon.com/dp/B07RLRP8QS?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Camp Stove", "USB Charger", "Wood Burning", "Off-Grid"],
    dateAdded: "2024-12-29",
  },
  {
    id: "p-057",
    title: "Goal Zero Nomad 50 Portable Solar Panel",
    slug: "goal-zero-nomad-50-portable-solar-panel",
    price: 249.95,
    originalPrice: 323.13,
    image: "https://m.media-amazon.com/images/I/71YVJH6cLPL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "50W monocrystalline solar panel with USB-C PD and USB-A outputs. Foldable and portable. Pairs with Goal Zero power stations.",
    rating: 4.5,
    reviewCount: 2200,
    affiliateUrl: "https://www.amazon.com/dp/B08PFJHPWG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Solar Panel", "Portable", "USB-C", "Goal Zero"],
    isFeatured: true,
    dateAdded: "2025-02-24",
  },
  {
    id: "p-058",
    title: "DJI Mini 4 Pro Drone with RC 2 Controller",
    slug: "dji-mini-4-pro-drone-with-rc-2-controller",
    price: 759.0,
    image: "https://m.media-amazon.com/images/I/61nLdgVMVkL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "Under 249g with 4K/100fps HDR video. Omnidirectional obstacle sensing. 34-min max flight time. ActiveTrack 360° subject tracking.",
    rating: 4.6,
    reviewCount: 3800,
    affiliateUrl: "https://www.amazon.com/dp/B0CHKJXKVY?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Drone", "4K", "DJI", "Lightweight"],
    dateAdded: "2024-12-21",
  },
  {
    id: "p-059",
    title: "Garmin GPSMAP 67 Handheld GPS Navigator",
    slug: "garmin-gpsmap-67-handheld-gps-navigator",
    price: 449.99,
    image: "https://m.media-amazon.com/images/I/71Wq3sMjYsL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "Multi-band GNSS with 3-inch sunlight-readable display. Preloaded TopoActive maps. inReach satellite communication compatible. 180-hour battery in expedition mode.",
    rating: 4.5,
    reviewCount: 1800,
    affiliateUrl: "https://www.amazon.com/dp/B0BWMQNB9V?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["GPS Navigator", "Handheld", "Garmin", "Topo Maps"],
    isNew: true,
    dateAdded: "2024-12-03",
  },
  {
    id: "p-060",
    title: "NITECORE TIKI UV Keychain Flashlight",
    slug: "nitecore-tiki-uv-keychain-flashlight",
    price: 29.95,
    image: "https://m.media-amazon.com/images/I/51+hXPMqhEL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "Ultra-compact rechargeable keychain light with 300 lumens. UV light mode for authentication. USB-C rechargeable. IP66 water resistant.",
    rating: 4.4,
    reviewCount: 8500,
    affiliateUrl: "https://www.amazon.com/dp/B07XNQFXVK?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Flashlight", "Keychain", "UV", "Rechargeable"],
    dateAdded: "2025-02-11",
  },
  {
    id: "p-061",
    title: "Garmin Overlander All-Terrain GPS Navigator",
    slug: "garmin-overlander-all-terrain-gps-navigator",
    price: 599.99,
    image: "https://m.media-amazon.com/images/I/71YB3VDTXRL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "7-inch rugged GPS with topographic maps, public land boundaries, and iOverlander POIs. Built-in barometer, compass, and altimeter.",
    rating: 4.3,
    reviewCount: 1200,
    affiliateUrl: "https://www.amazon.com/dp/B07VYD5LR8?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["GPS", "Overlanding", "Off-Road", "Garmin"],
    isFeatured: true,
    dateAdded: "2025-02-24",
  },
  {
    id: "p-062",
    title: "Black Diamond Spot 400 Headlamp",
    slug: "black-diamond-spot-400-headlamp",
    price: 39.95,
    image: "https://m.media-amazon.com/images/I/71VuSAa5qBL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "400 lumens with PowerTap dimming. Red night vision mode. IPX8 waterproof. 200-hour burn time on low. Compact and lightweight.",
    rating: 4.7,
    reviewCount: 15000,
    affiliateUrl: "https://www.amazon.com/dp/B09MFNXHYY?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Headlamp", "Waterproof", "Camping", "Hiking"],
    isTrending: true,
    dateAdded: "2024-12-20",
  },
  {
    id: "p-063",
    title: "Insta360 X4 360° Action Camera",
    slug: "insta360-x4-360°-action-camera",
    price: 499.99,
    image: "https://m.media-amazon.com/images/I/61Tn3tJmSYL._AC_SL1500_.jpg",
    category: "Outdoor & Adventure Tech",
    categorySlug: "outdoor-tech",
    description: "8K 360° video with FlowState stabilization. AI-powered reframing. Waterproof to 10m. 135-min battery life. Invisible selfie stick effect.",
    rating: 4.4,
    reviewCount: 2500,
    affiliateUrl: "https://www.amazon.com/dp/B0D2DXMHZ9?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["360 Camera", "8K", "Action Camera", "Insta360"],
    isTrending: true,
    dateAdded: "2025-01-30",
  },
  {
    id: "p-064",
    title: "Anker 737 Power Bank 24,000mAh 140W",
    slug: "anker-737-power-bank-24000mah-140w",
    price: 109.99,
    originalPrice: 146.41,
    image: "https://m.media-amazon.com/images/I/71ypQbiPpKL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "140W bidirectional charging with 24,000mAh capacity. Smart digital display. Charges MacBook Pro to 50% in 30 minutes. 3-port output.",
    rating: 4.6,
    reviewCount: 12500,
    affiliateUrl: "https://www.amazon.com/dp/B09VPHVT2Z?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Power Bank", "USB-C", "140W", "Anker"],
    dateAdded: "2025-02-26",
  },
  {
    id: "p-065",
    title: "CalDigit TS4 Thunderbolt 4 Dock (18 Ports)",
    slug: "caldigit-ts4-thunderbolt-4-dock-18-ports",
    price: 379.99,
    originalPrice: 492.79,
    image: "https://m.media-amazon.com/images/I/71yvJbSN-oL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "18 ports including 3x Thunderbolt 4, 5x USB-A, SD/microSD, 2.5GbE, and DisplayPort 1.4. 98W laptop charging. Aluminum enclosure.",
    rating: 4.6,
    reviewCount: 4200,
    affiliateUrl: "https://www.amazon.com/dp/B09GK8LBWS?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Thunderbolt Dock", "USB-C Hub", "CalDigit", "18 Ports"],
    dateAdded: "2025-01-29",
  },
  {
    id: "p-066",
    title: "Apple MagSafe Charger with 15W Fast Charging",
    slug: "apple-magsafe-charger-with-15w-fast-charging",
    price: 39.0,
    originalPrice: 51.85,
    image: "https://m.media-amazon.com/images/I/71QLCfGBpAL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Perfectly aligned magnets for effortless wireless charging. 15W fast charging for iPhone. Compatible with MagSafe cases and accessories.",
    rating: 4.6,
    reviewCount: 52000,
    affiliateUrl: "https://www.amazon.com/dp/B09G9BL2TP?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Wireless Charger", "MagSafe", "Apple", "15W"],
    isFeatured: true,
    dateAdded: "2025-02-01",
  },
  {
    id: "p-067",
    title: "Bellroy Tech Kit Compact Organizer",
    slug: "bellroy-tech-kit-compact-organizer",
    price: 59.0,
    originalPrice: 67.75,
    image: "https://m.media-amazon.com/images/I/71fSJHJVPQL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Premium woven fabric tech organizer with zippered mesh pockets, elastic loops, and padded compartments. Fits cables, chargers, and small devices.",
    rating: 4.6,
    reviewCount: 3800,
    affiliateUrl: "https://www.amazon.com/dp/B0BFCWB3Z6?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Tech Pouch", "Organizer", "Bellroy", "EDC"],
    dateAdded: "2025-02-01",
  },
  {
    id: "p-068",
    title: "Roost V3 Portable Laptop Stand",
    slug: "roost-v3-portable-laptop-stand",
    price: 74.95,
    image: "https://m.media-amazon.com/images/I/51aNqvVmxDL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Ultra-portable laptop stand weighing just 6oz. Adjustable height from 6-12 inches. Fits laptops 11-16 inches. Folds flat for travel.",
    rating: 4.6,
    reviewCount: 8500,
    affiliateUrl: "https://www.amazon.com/dp/B01C9KG8IG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Laptop Stand", "Portable", "Ergonomic", "Travel"],
    dateAdded: "2025-01-25",
  },
  {
    id: "p-069",
    title: "Peak Design Everyday Backpack V2 20L",
    slug: "peak-design-everyday-backpack-v2-20l",
    price: 259.95,
    image: "https://m.media-amazon.com/images/I/71QhQ+qlAYL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Versatile 20L backpack with FlexFold dividers, MagLatch closure, and weatherproof 400D nylon canvas. Fits 16-inch laptop. Lifetime guarantee.",
    rating: 4.6,
    reviewCount: 5200,
    affiliateUrl: "https://www.amazon.com/dp/B07YSJXKZ5?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Backpack", "Peak Design", "Camera Bag", "Travel"],
    dateAdded: "2025-01-18",
  },
  {
    id: "p-070",
    title: "Anker USB-C to USB-C Cable 100W (6ft, 2-Pack)",
    slug: "anker-usb-c-to-usb-c-cable-100w-6ft-2-pack",
    price: 15.99,
    originalPrice: 19.97,
    image: "https://m.media-amazon.com/images/I/61TnzVRNHzL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "100W Power Delivery for fast charging laptops and phones. USB 2.0 data transfer. Braided nylon cable with 12,000+ bend lifespan.",
    rating: 4.7,
    reviewCount: 65000,
    affiliateUrl: "https://www.amazon.com/dp/B09LCJPZ1P?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["USB-C Cable", "100W", "Fast Charging", "Anker"],
    isFeatured: true,
    isTrending: true,
    dateAdded: "2025-01-27",
  },
  {
    id: "p-071",
    title: "Samsung T7 Shield 2TB Portable SSD",
    slug: "samsung-t7-shield-2tb-portable-ssd",
    price: 159.99,
    originalPrice: 211.97,
    image: "https://m.media-amazon.com/images/I/71CIWezpKWL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Up to 1,050MB/s transfer speed with USB 3.2 Gen 2. IP65 water and dust resistant. Drop resistant up to 3m. Compact and rugged.",
    rating: 4.7,
    reviewCount: 18000,
    affiliateUrl: "https://www.amazon.com/dp/B09VLJB2DC?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Portable SSD", "2TB", "Samsung", "Rugged"],
    dateAdded: "2024-12-26",
  },
  {
    id: "p-072",
    title: "Leatherman Wave+ Multi-Tool",
    slug: "leatherman-wave-multi-tool",
    price: 99.95,
    image: "https://m.media-amazon.com/images/I/71S-DPjFRyL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "18 tools including pliers, wire cutters, knives, saw, and scissors. All-locking blades. Stainless steel construction. 25-year warranty.",
    rating: 4.8,
    reviewCount: 32000,
    affiliateUrl: "https://www.amazon.com/dp/B079MJBP71?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Multi-Tool", "Leatherman", "EDC", "Stainless Steel"],
    isNew: true,
    dateAdded: "2024-12-25",
  },
  {
    id: "p-073",
    title: "Nomad Base One Max MagSafe Charger",
    slug: "nomad-base-one-max-magsafe-charger",
    price: 109.95,
    originalPrice: 132.8,
    image: "https://m.media-amazon.com/images/I/61LpE-JQCBL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Official MFi MagSafe charger with metal and glass design. 15W wireless charging for iPhone. Weighted base prevents sliding.",
    rating: 4.4,
    reviewCount: 2800,
    affiliateUrl: "https://www.amazon.com/dp/B0BFHM6YHG?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Wireless Charger", "MagSafe", "Nomad", "Premium"],
    dateAdded: "2024-12-06",
  },
  {
    id: "p-074",
    title: "KeySmart Max Tile Tracker Key Organizer",
    slug: "keysmart-max-tile-tracker-key-organizer",
    price: 49.99,
    image: "https://m.media-amazon.com/images/I/61qHG-XQVOL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Compact key organizer with built-in Tile tracker. Holds up to 14 keys. Rechargeable battery. LED flashlight. Find your keys with the Tile app.",
    rating: 4.3,
    reviewCount: 5500,
    affiliateUrl: "https://www.amazon.com/dp/B09JNPMPVY?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Key Organizer", "Tracker", "Tile", "EDC"],
    dateAdded: "2024-12-07",
  },
  {
    id: "p-075",
    title: "Anker Nano II 65W USB-C GaN Charger",
    slug: "anker-nano-ii-65w-usb-c-gan-charger",
    price: 35.99,
    image: "https://m.media-amazon.com/images/I/51TiHqpNEcL._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "65W GaN II charger 58% smaller than standard chargers. Powers laptops, tablets, and phones. ActiveShield 2.0 temperature monitoring.",
    rating: 4.7,
    reviewCount: 28000,
    affiliateUrl: "https://www.amazon.com/dp/B09C5RG6KV?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["GaN Charger", "65W", "USB-C", "Compact"],
    dateAdded: "2025-01-08",
  },
  {
    id: "p-076",
    title: "Apple AirTag 4-Pack Bluetooth Tracker",
    slug: "apple-airtag-4-pack-bluetooth-tracker",
    price: 79.99,
    image: "https://m.media-amazon.com/images/I/71gY9E+cTaS._AC_SL1500_.jpg",
    category: "Everyday Carry & Accessories",
    categorySlug: "everyday-carry",
    description: "Precision Finding with Ultra Wideband. Plays a sound to help locate items. Built-in speaker. Replaceable battery lasts over a year. IP67 water resistant.",
    rating: 4.7,
    reviewCount: 95000,
    affiliateUrl: "https://www.amazon.com/dp/B0D54JZTHY?tag=gadgetstyle-20",
    retailer: "Amazon",
    tags: ["Bluetooth Tracker", "Apple", "Find My", "AirTag"],
    isTrending: true,
    dateAdded: "2024-12-06",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "bp-1",
    title: "The Best Noise-Cancelling Headphones of 2025",
    slug: "best-noise-cancelling-headphones-2025",
    excerpt: "We tested the top ANC headphones from Sony, Bose, Apple, and Sennheiser to find the ultimate pair for commuters, travelers, and audiophiles.",
    content: "Noise-cancelling headphones have become essential for modern life. Whether you are commuting on a noisy train, working in a busy office, or traveling long-haul, a great pair of ANC headphones can transform your experience. In this comprehensive review, we put the top contenders through rigorous testing across noise cancellation performance, sound quality, comfort, battery life, and value for money.",
    author: "Alex Chen",
    date: "2025-03-15",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=500&fit=crop",
    tags: ["Audio", "Headphones", "Reviews"],
  },
  {
    id: "bp-2",
    title: "Smart Home Essentials: Building Your Connected Home",
    slug: "smart-home-essentials-guide",
    excerpt: "From voice assistants to robot vacuums, here is everything you need to build a truly smart home in 2025.",
    content: "The smart home revolution is no longer a futuristic dream — it is happening right now in millions of homes worldwide. With the right combination of devices, you can automate your lighting, secure your property, manage your energy usage, and even have a robot clean your floors while you are at work. This guide walks you through the essential categories and our top picks in each.",
    author: "Sarah Mitchell",
    date: "2025-03-10",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=500&fit=crop",
    tags: ["Smart Home", "Guide", "IoT"],
  },
  {
    id: "bp-3",
    title: "GoPro HERO13 vs DJI Action 5 Pro: Which Action Camera Wins?",
    slug: "gopro-hero13-vs-dji-action-5-pro",
    excerpt: "Two action camera titans go head-to-head. We compare video quality, stabilization, battery life, and value.",
    content: "The action camera market has never been more competitive, and the battle between GoPro and DJI continues to push innovation forward. Both the HERO13 Black and the Osmo Action 5 Pro offer incredible 4K+ video, advanced stabilization, and rugged waterproof designs. But which one deserves a spot in your adventure kit? We break down every aspect to help you decide.",
    author: "Jake Torres",
    date: "2025-03-05",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&h=500&fit=crop",
    tags: ["Cameras", "Comparison", "Outdoor"],
  },
  {
    id: "bp-4",
    title: "The Rise of Smart Rings: Oura, Samsung, and Beyond",
    slug: "rise-of-smart-rings",
    excerpt: "Smart rings are the next frontier in wearable tech. We explore the best options for health tracking without a screen.",
    content: "Smart rings represent a paradigm shift in wearable technology. Unlike smartwatches with their bright screens and constant notifications, smart rings offer discreet, always-on health monitoring in a form factor that looks like regular jewelry. The Oura Ring Gen 3 pioneered this space, and now Samsung and others are entering the arena with compelling alternatives.",
    author: "Maya Patel",
    date: "2025-02-28",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&h=500&fit=crop",
    tags: ["Wearables", "Health", "Trends"],
  },
  {
    id: "bp-5",
    title: "Ultimate EDC Tech Kit: What We Carry Every Day",
    slug: "ultimate-edc-tech-kit",
    excerpt: "Our editors share the essential tech accessories they never leave home without — from power banks to multi-tools.",
    content: "Every day carry is about having the right tools at hand for whatever the day throws at you. Our editorial team has tested hundreds of tech accessories, and these are the ones that have earned a permanent spot in our bags. From the perfect power bank to the most versatile multi-tool, here is our curated EDC tech kit.",
    author: "Alex Chen",
    date: "2025-02-20",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=500&fit=crop",
    tags: ["EDC", "Accessories", "Lifestyle"],
  },
  {
    id: "bp-6",
    title: "Gaming Setup Guide: Build the Perfect Battlestation",
    slug: "gaming-setup-guide-2025",
    excerpt: "From monitors to keyboards, mice, and headsets — our complete guide to building a pro-level gaming setup.",
    content: "Building the perfect gaming setup is both an art and a science. It requires balancing performance, ergonomics, aesthetics, and budget. Whether you are a competitive esports player or a casual gamer who wants an immersive experience, the right peripherals can make all the difference. This guide covers every component of a modern battlestation.",
    author: "Jake Torres",
    date: "2025-02-15",
    readTime: "15 min read",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=500&fit=crop",
    tags: ["Gaming", "Guide", "Setup"],
  },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getTrendingProducts(): Product[] {
  return products.filter((p) => p.isTrending);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((bp) => bp.slug === slug);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category.toLowerCase().includes(q)
  );
}

