/**
 * Generate docs/placeholder-products.md — a triage report of products that
 * look like Manus-era placeholders (fabricated ASINs, zero prices, duplicate
 * ASINs across unrelated products).
 *
 * This does NOT modify data.ts. It's a read-only report for human review.
 * Re-run any time: `pnpm tsx scripts/report-placeholders.ts`.
 */

import { products } from "../client/src/lib/data.js";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const OUT_DIR = join(REPO_ROOT, "docs");
const OUT_PATH = join(OUT_DIR, "placeholder-products.md");

const ASIN_RE = /^B0[A-Z0-9]{8}$/;

// Reasons a product is flagged.
type Flag = "bad-asin-format" | "price-zero" | "duplicate-asin";
const flagged = new Map<number, { flags: Set<Flag>; conflicts?: number[] }>();

function flag(id: number, f: Flag, conflictId?: number) {
  if (!flagged.has(id)) flagged.set(id, { flags: new Set(), conflicts: [] });
  const entry = flagged.get(id)!;
  entry.flags.add(f);
  if (conflictId !== undefined) entry.conflicts!.push(conflictId);
}

for (const p of products) {
  if (!ASIN_RE.test(p.asin)) flag(p.id, "bad-asin-format");
  if (typeof p.price !== "number" || p.price <= 0) flag(p.id, "price-zero");
}

const asinMap = new Map<string, number[]>();
for (const p of products) {
  if (!ASIN_RE.test(p.asin)) continue;
  if (!asinMap.has(p.asin)) asinMap.set(p.asin, []);
  asinMap.get(p.asin)!.push(p.id);
}
for (const [, ids] of asinMap) {
  if (ids.length > 1) for (const id of ids) flag(id, "duplicate-asin", ids.find((x) => x !== id));
}

if (flagged.size === 0) {
  console.log("No placeholder products detected.");
  process.exit(0);
}

const lines: string[] = [];
lines.push("# Placeholder products — needs human review\n");
lines.push(
  `Generated by \`scripts/report-placeholders.ts\`. Updated: ${new Date().toISOString().slice(0, 10)}.\n`,
);
lines.push(
  "These entries in `client/src/lib/data.ts` have markers of being fabricated or " +
    "aspirational rather than real purchasable listings. Each must be resolved before " +
    "the site is considered production-ready — pick one of:\n",
);
lines.push(
  "1. **Verify** against the real Amazon listing: fix the ASIN, update affiliate URL via " +
    "`pnpm tsx scripts/fix-affiliate-urls.ts`, fix the price.\n",
);
lines.push("2. **Remove** the product from `data.ts`.\n");
lines.push(
  "3. **Convert to search-style affiliate link** (temporary): change `affiliateUrl` to " +
    "`https://www.amazon.com/s?k=<encoded-title>&tag=gadgetstyle01-20` once a real ASIN " +
    "becomes available.\n",
);
lines.push(`\n---\n\n**${flagged.size} flagged products**\n`);

const rows: string[] = [
  "| id | title | asin | price | flags | conflicts |",
  "|----|-------|------|-------|-------|-----------|",
];
const sortedIds = [...flagged.keys()].sort((a, b) => a - b);
for (const id of sortedIds) {
  const p = products.find((x) => x.id === id)!;
  const entry = flagged.get(id)!;
  const flagStr = [...entry.flags].join(", ");
  const conflictStr = entry.conflicts && entry.conflicts.length ? entry.conflicts.filter(Boolean).join(", ") : "";
  const title = p.title.length > 50 ? p.title.slice(0, 47) + "..." : p.title;
  rows.push(`| ${p.id} | ${title} | \`${p.asin}\` | ${p.price} | ${flagStr} | ${conflictStr} |`);
}
lines.push(rows.join("\n"));
lines.push("");

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n"));
console.log(`wrote ${OUT_PATH} — ${flagged.size} flagged products`);
